version: "3.8"

services:
  blog:
    build: ./blog
    container_name: blog_site
    volumes:
      - ./logo.png:/usr/share/nginx/html/logo.png
    ports:
      - "8090:80"

  event:
    build: ./event
    container_name: event_site
    volumes:
      - ./logo.png:/usr/share/nginx/html/logo.png
    ports:
      - "8091:80"

  portfolio:
    build: ./portfolio
    container_name: portfolio_site
    volumes:
      - ./logo.png:/usr/share/nginx/html/logo.png
    ports:
      - "8092:80"

  restaurant:
    build: ./restaurant
    container_name: restaurant_site
    volumes:
      - ./logo.png:/usr/share/nginx/html/logo.png
    ports:
      - "8093:80"

  startup:
    build: ./startup
    volumes:
      - ./logo.png:/usr/share/nginx/html/logo.png
    container_name: startup_site
    ports:
      - "8094:80"

  personal_website1:
    build: ./website
    container_name: personal_website1
    ports:
      - "8095:80"

  personal_website2:
    build: ./website
    container_name: personal_website2
    ports:
      - "8096:80"
  
  personal_website3:
    build: ./website
    container_name: personal_website3
    ports:
      - "8097:80"

  personal_website4:
    build: ./website
    container_name: personal_website4
    ports:
      - "8098:80"

  personal_website5:
    build: ./website
    container_name: personal_website5
    ports:
      - "8099:80"